# Generated by Django 4.0.4 on 2022-05-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ost_index',
        ),
        migrations.RemoveField(
            model_name='game',
            name='song',
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=2083)),
                ('name', models.CharField(max_length=255)),
                ('ost_index', models.IntegerField()),
                ('description', models.CharField(max_length=2083)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
