# Generated by Django 4.0.4 on 2022-05-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_ost_index_remove_game_song_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.CharField(default=' ', max_length=2083),
            preserve_default=False,
        ),
    ]
